namespaces:
  Magus\Core\Database:    magus/core/database
  Magus\Core\Defaults:    magus/core/defaults
  Magus\Core\Theme:       magus/core/theme
  Magus\Core\Plugin:      magus/core/plugin

  Magus\Plugins:          magus/plugins
  Magus\Themes:           magus/themes

application:
  name: App
  admin_url: admin
  admin_path: admin
  theme: default
  path: app

sessions:
  session_name: magus_secure_session
  secure_connections_only: false

authentication:
  password_salt:
  hash_algorithm: sha512

plugins:
  Home:
    enabled: true
    path: magus/core/defaults/Home
    namespace_prefix: Magus\Core\Defaults
